name: Update Stella

on:
  workflow_dispatch:
    schedule:
      # run every 5 minutes
      - cron: '*/5 * * * *'

jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Set Timezone
        run: |
          sudo timedatectl set-timezone Asia/Seoul

      - name: Dependencies
        run: |
          pip3 install requests

      - name: Add mask
        run: |
          echo "::add-mask::${{ secrets.MASK_IP }}"
          echo "::add-mask::${{ secrets.PROJECT_ID }}"

      - name: Configure the Google Cloud CLI
        run: |
          curl -L -s ${{ secrets.SERVICE_ACCOUNT_JSON }} -o /tmp/service-account.json
          gcloud auth activate-service-account ${{ secrets.SERVICE_ACCOUNT_EMAIL }} --key-file=/tmp/service-account.json
          rm /tmp/service-account.json
          gcloud config set project ${{ secrets.PROJECT_ID }} -q

      - name: Update.py
        env:
          MISSKEY_CREDENTIAL: ${{ secrets.MISSKEY_CREDENTIAL }}
        run: |
          python3 /home/runner/work/workflows/workflows/bin/update-stella.py
